/*
 * Copyright © 2023 FundamentalVR Ltd. hello@fundamentalsurgery.com. All rights reserved.
 * 
 * Use of this software is subject to compliance with the licence terms and conditions.
 */

namespace Fvr.SDK.Common
{
	/// This file is automatically generated. Any changes made will be overwritten on the next 
	/// localisation import.

	/// <summary>
	/// StringID const class for the LocalisedStringID strings
	/// </summary>
	public partial class LocalisedStringID
	{
		/// <summary> Example SDK Application </summary>
		public const string APPLICATION_NAME = "APPLICATION_NAME";
		/// <summary> Discipline </summary>
		public const string APPLICATION_DISCIPLINE = "APPLICATION_DISCIPLINE";
		/// <summary> SubDiscipline </summary>
		public const string APPLICATION_SUB_DISCIPLINE = "APPLICATION_SUB_DISCIPLINE";
		/// <summary> Single Player Example </summary>
		public const string MOD_01_NAME = "MOD_01_NAME";
		/// <summary> Module 01 Speciality </summary>
		public const string MOD_01_SPECIALITY = "MOD_01_SPECIALITY";
		/// <summary> Example single player module </summary>
		public const string MOD_01_SUMMARY = "MOD_01_SUMMARY";
		/// <summary> This is an example of a single player module and includes multiple different steps including assessed steps.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut. </summary>
		public const string MOD_01_DESCRIPTION = "MOD_01_DESCRIPTION";
		/// <summary> Logging Out,\nPlease Wait </summary>
		public const string LOGGING_OUT_WAIT = "LOGGING_OUT_WAIT";
		/// <summary> Returning to the Lobby,\nPlease Wait </summary>
		public const string RETURN_TO_LOBBY_WAIT = "RETURN_TO_LOBBY_WAIT";
		/// <summary> Unit 1 </summary>
		public const string MOD_01_UNIT_00_NAME = "MOD_01_UNIT_00_NAME";
		/// <summary> Step 1 </summary>
		public const string MOD_01_STEP_00_NAME = "MOD_01_STEP_00_NAME";
		/// <summary> Step 2 </summary>
		public const string MOD_01_STEP_01_NAME = "MOD_01_STEP_01_NAME";
		/// <summary> Step 3 </summary>
		public const string MOD_01_STEP_02_NAME = "MOD_01_STEP_02_NAME";
		/// <summary> Step 3A </summary>
		public const string MOD_01_STEP_02_SUB_A_NAME = "MOD_01_STEP_02_SUB_A_NAME";
		/// <summary> Step 3B </summary>
		public const string MOD_01_STEP_02_SUB_B_NAME = "MOD_01_STEP_02_SUB_B_NAME";
		/// <summary> Step 4 </summary>
		public const string MOD_01_STEP_03_NAME = "MOD_01_STEP_03_NAME";
		/// <summary> Step 5 </summary>
		public const string MOD_01_STEP_04_NAME = "MOD_01_STEP_04_NAME";
		/// <summary> Step 6 </summary>
		public const string MOD_01_STEP_05_NAME = "MOD_01_STEP_05_NAME";
		/// <summary> Step 7 </summary>
		public const string MOD_01_STEP_06_NAME = "MOD_01_STEP_06_NAME";
		/// <summary> Unit 2 </summary>
		public const string MOD_01_UNIT_01_NAME = "MOD_01_UNIT_01_NAME";
		/// <summary> Step 8 </summary>
		public const string MOD_01_STEP_07_NAME = "MOD_01_STEP_07_NAME";
		/// <summary> Step 9 </summary>
		public const string MOD_01_STEP_08_NAME = "MOD_01_STEP_08_NAME";
		/// <summary> Step 1 Title </summary>
		public const string MOD_01_PAGE_INFO_GENERIC_0_TITLE = "MOD_01_PAGE_INFO_GENERIC_0_TITLE";
		/// <summary> Step 1 Subtitle </summary>
		public const string MOD_01_PAGE_INFO_GENERIC_0_SUBTITLE = "MOD_01_PAGE_INFO_GENERIC_0_SUBTITLE";
		/// <summary> The first step is an example of a non assessed information step.\n\nOnce the user has read the text, they are instructed to press the <b>NEXT</b> button to advance to the next step.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Ut. </summary>
		public const string MOD_01_PAGE_INFO_GENERIC_0_INSTRUCTIONS = "MOD_01_PAGE_INFO_GENERIC_0_INSTRUCTIONS";
		/// <summary> Step 1 image description </summary>
		public const string MOD_01_PAGE_INFO_GENERIC_0_FIRST_IMAGE_TEXT = "MOD_01_PAGE_INFO_GENERIC_0_FIRST_IMAGE_TEXT";
		/// <summary> Step 2 Title </summary>
		public const string MOD_01_PAGE_INFO_GENERIC_1_TITLE = "MOD_01_PAGE_INFO_GENERIC_1_TITLE";
		/// <summary> Step 2 first image description </summary>
		public const string MOD_01_PAGE_INFO_GENERIC_1_FIRST_IMAGE_TEXT = "MOD_01_PAGE_INFO_GENERIC_1_FIRST_IMAGE_TEXT";
		/// <summary> Step 2 second image description </summary>
		public const string MOD_01_PAGE_INFO_GENERIC_1_SECOND_IMAGE_TEXT = "MOD_01_PAGE_INFO_GENERIC_1_SECOND_IMAGE_TEXT";
		/// <summary> Step 3 Title </summary>
		public const string MOD_01_PAGE_INFO_GENERIC_2_TITLE = "MOD_01_PAGE_INFO_GENERIC_2_TITLE";
		/// <summary> Interaction </summary>
		public const string MOD_01_PAGE_INFO_GENERIC_2_SUBTITLE = "MOD_01_PAGE_INFO_GENERIC_2_SUBTITLE";
		/// <summary> The third step is an example of an interaction step.\n\nThe user is given a set of instructions to complete.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </summary>
		public const string MOD_01_PAGE_INFO_GENERIC_2_INSTRUCTIONS = "MOD_01_PAGE_INFO_GENERIC_2_INSTRUCTIONS";
		/// <summary> Step 3 Title </summary>
		public const string MOD_01_PAGE_INFO_GENERIC_2B_TITLE = "MOD_01_PAGE_INFO_GENERIC_2B_TITLE";
		/// <summary> Interaction Feedback </summary>
		public const string MOD_01_PAGE_INFO_GENERIC_2B_SUBTITLE = "MOD_01_PAGE_INFO_GENERIC_2B_SUBTITLE";
		/// <summary> The user is informed whether or not they have passed or failed the step.\n\nFor this example, the user has failed the assessment.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu. </summary>
		public const string MOD_01_PAGE_INFO_GENERIC_2B_INSTRUCTIONS = "MOD_01_PAGE_INFO_GENERIC_2B_INSTRUCTIONS";
		/// <summary> Step 4 Title </summary>
		public const string MOD_01_PAGE_INFO_GENERIC_3_TITLE = "MOD_01_PAGE_INFO_GENERIC_3_TITLE";
		/// <summary> The forth step is an example of a non assessed animation step. Once the animation has finished playing, the user is instructed to press the <b>NEXT</b> button to advance to the next step. </summary>
		public const string MOD_01_PAGE_INFO_GENERIC_3_INSTRUCTIONS = "MOD_01_PAGE_INFO_GENERIC_3_INSTRUCTIONS";
		/// <summary> Step 4 image description </summary>
		public const string MOD_01_PAGE_INFO_GENERIC_3_FIRST_IMAGE_TEXT = "MOD_01_PAGE_INFO_GENERIC_3_FIRST_IMAGE_TEXT";
		/// <summary> Step 5 - Interaction </summary>
		public const string MOD_01_PAGE_INFO_GENERIC_4_TITLE = "MOD_01_PAGE_INFO_GENERIC_4_TITLE";
		/// <summary> The fifth step is an example of an interaction step.\n\nThe user is given a set of instructions to complete.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea. </summary>
		public const string MOD_01_PAGE_INFO_GENERIC_4_INSTRUCTIONS = "MOD_01_PAGE_INFO_GENERIC_4_INSTRUCTIONS";
		/// <summary> Step 5 image description </summary>
		public const string MOD_01_PAGE_INFO_GENERIC_4_FIRST_IMAGE_TEXT = "MOD_01_PAGE_INFO_GENERIC_4_FIRST_IMAGE_TEXT";
		/// <summary> Step 5 - Feedback </summary>
		public const string MOD_01_PAGE_INFO_GENERIC_4B_TITLE = "MOD_01_PAGE_INFO_GENERIC_4B_TITLE";
		/// <summary> The user is informed whether or not they have passed or failed the step.\n\nFor this example, the user has passed the assessment.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu. </summary>
		public const string MOD_01_PAGE_INFO_GENERIC_4B_INSTRUCTIONS = "MOD_01_PAGE_INFO_GENERIC_4B_INSTRUCTIONS";
		/// <summary> Step 6 Title </summary>
		public const string MOD_01_PAGE_INFO_GENERIC_5_TITLE = "MOD_01_PAGE_INFO_GENERIC_5_TITLE";
		/// <summary> Step 6 image description </summary>
		public const string MOD_01_PAGE_INFO_GENERIC_5_FIRST_IMAGE_TEXT = "MOD_01_PAGE_INFO_GENERIC_5_FIRST_IMAGE_TEXT";
		/// <summary> Step 7 Title </summary>
		public const string MOD_01_PAGE_INFO_GENERIC_6_TITLE = "MOD_01_PAGE_INFO_GENERIC_6_TITLE";
		/// <summary> Step 8 Title </summary>
		public const string MOD_01_PAGE_INFO_GENERIC_7_TITLE = "MOD_01_PAGE_INFO_GENERIC_7_TITLE";
		/// <summary> Step 8 image description </summary>
		public const string MOD_01_PAGE_INFO_GENERIC_7_FIRST_IMAGE_TEXT = "MOD_01_PAGE_INFO_GENERIC_7_FIRST_IMAGE_TEXT";
		/// <summary> The eigth step is an example of a non assessed information step.\n\nOnce the user has read the text, they are instructed to press the <b>NEXT</b> button to advance to the next step.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Integer pharetra facilisis. </summary>
		public const string MOD_01_PAGE_INFO_GENERIC_7_INSTRUCTIONS = "MOD_01_PAGE_INFO_GENERIC_7_INSTRUCTIONS";
		/// <summary> Step 9 Title </summary>
		public const string MOD_01_PAGE_INFO_GENERIC_8_TITLE = "MOD_01_PAGE_INFO_GENERIC_8_TITLE";
		/// <summary> Step 9 Subtitle </summary>
		public const string MOD_01_PAGE_INFO_GENERIC_8_SUBTITLE = "MOD_01_PAGE_INFO_GENERIC_8_SUBTITLE";
		/// <summary> The ninth step is an example of a non assessed animation step.\n\nOnce the animation has finished playing, the user is instructed to press the <b>NEXT</b> button to advance to the next step.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </summary>
		public const string MOD_01_PAGE_INFO_GENERIC_8_INSTRUCTIONS = "MOD_01_PAGE_INFO_GENERIC_8_INSTRUCTIONS";
		/// <summary> This is an example of a multi user module and includes multiple different steps including assessed steps.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut. </summary>
		public const string MOD_02_DESCRIPTION = "MOD_02_DESCRIPTION";
		/// <summary> Multi User Example </summary>
		public const string MOD_02_NAME = "MOD_02_NAME";
		/// <summary> Module 02 Speciality </summary>
		public const string MOD_02_SPECIALITY = "MOD_02_SPECIALITY";
		/// <summary> Example multi user module </summary>
		public const string MOD_02_SUMMARY = "MOD_02_SUMMARY";
		/// <summary> Step 1 </summary>
		public const string MOD_02_STEP_00_NAME = "MOD_02_STEP_00_NAME";
		/// <summary> Step 2 </summary>
		public const string MOD_02_STEP_01_NAME = "MOD_02_STEP_01_NAME";
		/// <summary> Step 3 </summary>
		public const string MOD_02_STEP_02_NAME = "MOD_02_STEP_02_NAME";
		/// <summary> Step 3A </summary>
		public const string MOD_02_STEP_02_SUB_A_NAME = "MOD_02_STEP_02_SUB_A_NAME";
		/// <summary> Step 3B </summary>
		public const string MOD_02_STEP_02_SUB_B_NAME = "MOD_02_STEP_02_SUB_B_NAME";
		/// <summary> Step 4 </summary>
		public const string MOD_02_STEP_03_NAME = "MOD_02_STEP_03_NAME";
		/// <summary> Step 5 </summary>
		public const string MOD_02_STEP_04_NAME = "MOD_02_STEP_04_NAME";
		/// <summary> Step 6 </summary>
		public const string MOD_02_STEP_05_NAME = "MOD_02_STEP_05_NAME";
		/// <summary> Step 7 </summary>
		public const string MOD_02_STEP_06_NAME = "MOD_02_STEP_06_NAME";
		/// <summary> Step 8 </summary>
		public const string MOD_02_STEP_07_NAME = "MOD_02_STEP_07_NAME";
		/// <summary> Step 9 </summary>
		public const string MOD_02_STEP_08_NAME = "MOD_02_STEP_08_NAME";
		/// <summary> Unit 1 </summary>
		public const string MOD_02_UNIT_00_NAME = "MOD_02_UNIT_00_NAME";
		/// <summary> Unit 2 </summary>
		public const string MOD_02_UNIT_01_NAME = "MOD_02_UNIT_01_NAME";
		/// <summary> Step 1 Title </summary>
		public const string MOD_02_PAGE_INFO_GENERIC_0_TITLE = "MOD_02_PAGE_INFO_GENERIC_0_TITLE";
		/// <summary> Step 1 Subtitle </summary>
		public const string MOD_02_PAGE_INFO_GENERIC_0_SUBTITLE = "MOD_02_PAGE_INFO_GENERIC_0_SUBTITLE";
		/// <summary> The first step is an example of a non assessed information step.\n\nOnce the user has read the text, they are instructed to press the <b>NEXT</b> button to advance to the next step.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Ut. </summary>
		public const string MOD_02_PAGE_INFO_GENERIC_0_INSTRUCTIONS = "MOD_02_PAGE_INFO_GENERIC_0_INSTRUCTIONS";
		/// <summary> Step 1 image description </summary>
		public const string MOD_02_PAGE_INFO_GENERIC_0_FIRST_IMAGE_TEXT = "MOD_02_PAGE_INFO_GENERIC_0_FIRST_IMAGE_TEXT";
		/// <summary> Step 2 Title </summary>
		public const string MOD_02_PAGE_INFO_GENERIC_1_TITLE = "MOD_02_PAGE_INFO_GENERIC_1_TITLE";
		/// <summary> Step 2 first image description </summary>
		public const string MOD_02_PAGE_INFO_GENERIC_1_FIRST_IMAGE_TEXT = "MOD_02_PAGE_INFO_GENERIC_1_FIRST_IMAGE_TEXT";
		/// <summary> Step 2 second image description </summary>
		public const string MOD_02_PAGE_INFO_GENERIC_1_SECOND_IMAGE_TEXT = "MOD_02_PAGE_INFO_GENERIC_1_SECOND_IMAGE_TEXT";
		/// <summary> Step 3 Title </summary>
		public const string MOD_02_PAGE_INFO_GENERIC_2_TITLE = "MOD_02_PAGE_INFO_GENERIC_2_TITLE";
		/// <summary> Interaction </summary>
		public const string MOD_02_PAGE_INFO_GENERIC_2_SUBTITLE = "MOD_02_PAGE_INFO_GENERIC_2_SUBTITLE";
		/// <summary> The third step is an example of an interaction step.\n\nThe user is given a set of instructions to complete.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </summary>
		public const string MOD_02_PAGE_INFO_GENERIC_2_INSTRUCTIONS = "MOD_02_PAGE_INFO_GENERIC_2_INSTRUCTIONS";
		/// <summary> Step 3 Title </summary>
		public const string MOD_02_PAGE_INFO_GENERIC_2B_TITLE = "MOD_02_PAGE_INFO_GENERIC_2B_TITLE";
		/// <summary> Interaction Feedback </summary>
		public const string MOD_02_PAGE_INFO_GENERIC_2B_SUBTITLE = "MOD_02_PAGE_INFO_GENERIC_2B_SUBTITLE";
		/// <summary> The user is informed whether or not they have passed or failed the step.\n\nFor this example, the user has failed the assessment.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu. </summary>
		public const string MOD_02_PAGE_INFO_GENERIC_2B_INSTRUCTIONS = "MOD_02_PAGE_INFO_GENERIC_2B_INSTRUCTIONS";
		/// <summary> Step 4 Title </summary>
		public const string MOD_02_PAGE_INFO_GENERIC_3_TITLE = "MOD_02_PAGE_INFO_GENERIC_3_TITLE";
		/// <summary> The forth step is an example of a non assessed animation step. Once the animation has finished playing, the user is instructed to press the <b>NEXT</b> button to advance to the next step. </summary>
		public const string MOD_02_PAGE_INFO_GENERIC_3_INSTRUCTIONS = "MOD_02_PAGE_INFO_GENERIC_3_INSTRUCTIONS";
		/// <summary> Step 4 image description </summary>
		public const string MOD_02_PAGE_INFO_GENERIC_3_FIRST_IMAGE_TEXT = "MOD_02_PAGE_INFO_GENERIC_3_FIRST_IMAGE_TEXT";
		/// <summary> Step 5 - Interaction </summary>
		public const string MOD_02_PAGE_INFO_GENERIC_4_TITLE = "MOD_02_PAGE_INFO_GENERIC_4_TITLE";
		/// <summary> The fifth step is an example of an interaction step.\n\nThe user is given a set of instructions to complete.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea. </summary>
		public const string MOD_02_PAGE_INFO_GENERIC_4_INSTRUCTIONS = "MOD_02_PAGE_INFO_GENERIC_4_INSTRUCTIONS";
		/// <summary> Step 5 image description </summary>
		public const string MOD_02_PAGE_INFO_GENERIC_4_FIRST_IMAGE_TEXT = "MOD_02_PAGE_INFO_GENERIC_4_FIRST_IMAGE_TEXT";
		/// <summary> Step 5 - Feedback </summary>
		public const string MOD_02_PAGE_INFO_GENERIC_4B_TITLE = "MOD_02_PAGE_INFO_GENERIC_4B_TITLE";
		/// <summary> The user is informed whether or not they have passed or failed the step.\n\nFor this example, the user has passed the assessment.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu. </summary>
		public const string MOD_02_PAGE_INFO_GENERIC_4B_INSTRUCTIONS = "MOD_02_PAGE_INFO_GENERIC_4B_INSTRUCTIONS";
		/// <summary> Step 6 Title </summary>
		public const string MOD_02_PAGE_INFO_GENERIC_5_TITLE = "MOD_02_PAGE_INFO_GENERIC_5_TITLE";
		/// <summary> Step 6 image description </summary>
		public const string MOD_02_PAGE_INFO_GENERIC_5_FIRST_IMAGE_TEXT = "MOD_02_PAGE_INFO_GENERIC_5_FIRST_IMAGE_TEXT";
		/// <summary> Step 7 Title </summary>
		public const string MOD_02_PAGE_INFO_GENERIC_6_TITLE = "MOD_02_PAGE_INFO_GENERIC_6_TITLE";
		/// <summary> Step 8 Title </summary>
		public const string MOD_02_PAGE_INFO_GENERIC_7_TITLE = "MOD_02_PAGE_INFO_GENERIC_7_TITLE";
		/// <summary> Step 8 image description </summary>
		public const string MOD_02_PAGE_INFO_GENERIC_7_FIRST_IMAGE_TEXT = "MOD_02_PAGE_INFO_GENERIC_7_FIRST_IMAGE_TEXT";
		/// <summary> The eigth step is an example of a non assessed information step.\n\nOnce the user has read the text, they are instructed to press the <b>NEXT</b> button to advance to the next step.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit. Integer pharetra facilisis. </summary>
		public const string MOD_02_PAGE_INFO_GENERIC_7_INSTRUCTIONS = "MOD_02_PAGE_INFO_GENERIC_7_INSTRUCTIONS";
		/// <summary> Step 9 Title </summary>
		public const string MOD_02_PAGE_INFO_GENERIC_8_TITLE = "MOD_02_PAGE_INFO_GENERIC_8_TITLE";
		/// <summary> Step 9 Subtitle </summary>
		public const string MOD_02_PAGE_INFO_GENERIC_8_SUBTITLE = "MOD_02_PAGE_INFO_GENERIC_8_SUBTITLE";
		/// <summary> The ninth step is an example of a non assessed animation step.\n\nOnce the animation has finished playing, the user is instructed to press the <b>NEXT</b> button to advance to the next step.\n\nLorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </summary>
		public const string MOD_02_PAGE_INFO_GENERIC_8_INSTRUCTIONS = "MOD_02_PAGE_INFO_GENERIC_8_INSTRUCTIONS";
		/// <summary> Description Here please </summary>
		public const string MOD_LUMBAR_DESCRIPTION = "MOD_LUMBAR_DESCRIPTION";
		/// <summary> Lumbar Puncture module. </summary>
		public const string MOD_LUMBAR_NAME = "MOD_LUMBAR_NAME";
		/// <summary> Module LUMBAR Speciality </summary>
		public const string MOD_LUMBAR_SPECIALITY = "MOD_LUMBAR_SPECIALITY";
		/// <summary> Example lumbar puncture module </summary>
		public const string MOD_LUMBAR_SUMMARY = "MOD_LUMBAR_SUMMARY";
		/// <summary> Unit 1 </summary>
		public const string MOD_LUMBAR_UNIT_00_NAME = "MOD_LUMBAR_UNIT_00_NAME";
		/// <summary> Step 1 </summary>
		public const string MOD_01_LUMBAR_00_NAME = "MOD_01_LUMBAR_00_NAME";
		/// <summary> Step 1 </summary>
		public const string MOD_LUMBAR_STEP_00_NAME = "MOD_LUMBAR_STEP_00_NAME";
		/// <summary> Step 1 Title </summary>
		public const string MOD_LUMBAR_PAGE_INFO_GENERIC_0_TITLE = "MOD_LUMBAR_PAGE_INFO_GENERIC_0_TITLE";

	}
}